### ISSUE TITLE
Panic on transposing high notes

### ISSUE THREAD

**Issue by stefreak** [emicklei/melrose#12]
I noticed when playing unrealistically high notes, there must be an integer overflow somewhere, high notes suddenly sound deep.

But when transposing the note additionally by an octave, I get a crash:

```
play(transpose(7,sequence('C10')))
2022/08/21 18:10:44 http: panic serving 127.0.0.1:57550: MIDI number must be in [0..127]
goroutine 10 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x442af80, 0xc000021070})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/emicklei/melrose/core.Note.Pitched({{0xc00002a2ce, 0x1}, 0xa, 0x0, 0x0, 0x3b, 0x3e800000, 0x0, {0x0, 0x0, ...}}, ...)
        /Users/emicklei/goProjects/github.com/emicklei/melrose/core/note_ops.go:13 +0x770
github.com/emicklei/melrose/core.Sequence.Pitched({{0xc00000e2b8?, 0xc000021000?, 0x40cf500?}}, 0x7)
        /Users/emicklei/goProjects/github.com/emicklei/melrose/core/sequence_ops.go:14 +0x2a5
github.com/emicklei/melrose/op.Transpose.S({{0x4547c40?, 0xc00000e2d0?}, {0x4546f40?, 0xc000021000?}})
        /Users/emicklei/goProjects/github.com/emicklei/melrose/op/transpose.go:15 +0x72
github.com/emicklei/melrose/midi.(*OutputDevice).Play(0xc000304960, 0x0, {0x4548000?, 0xc0000781a0?}, 0x4056766?, {0x4069100?, 0xc0003975b8?, 0x47c34c0?})
        /Users/emicklei/goProjects/github.com/emicklei/melrose/midi/output_device.go:96 +0x1b5
github.com/emicklei/melrose/midi.(*DeviceRegistry).Play(0xc00011b2f0, 0x1c?, {0x4548000?, 0xc0000781a0?}, 0xc00002e100?, {0x19?, 0x508c108?, 0x47c34c0?})
        /Users/emicklei/goProjects/github.com/emicklei/melrose/midi/play.go:41 +0x22b
github.com/emicklei/melrose/api.(*ServiceImpl).CommandPlay(0xc0001263d8, {0xc0000362d9?, 0x449b024?}, 0xf, {0xc00002e100, 0x19})
        /Users/emicklei/goProjects/github.com/emicklei/melrose/api/impl.go:92 +0x2b3
github.com/emicklei/melrose/server.(*LanguageServer).statementHandler(0xc00011b3b0, {0x454a528, 0xc000200380}, 0xc000214300)
        /Users/emicklei/goProjects/github.com/emicklei/melrose/server/statements.go:61 +0x974
net/http.HandlerFunc.ServeHTTP(0x200?, {0x454a528?, 0xc000200380?}, 0xc00006faa8?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0000362b4?, {0x454a528, 0xc000200380}, 0xc000214300)
        /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x45492f0?}, {0x454a528, 0xc000200380}, 0xc000214300)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0002221e0, {0x454a7b0, 0xc00007e150})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
```

This is obviously not very important to fix, but I wanted to create a GitHub issue for this.

Thank you for creating this interesting project!

**Comment by emicklei** [comment]
thank you for reporting this. 

Panics should be gracefully handled by an error message instead of program exit.

**Comment by emicklei** [comment]
with this change:

```
𝄞 play(transpose(7,sequence('C10')))
error:  MIDI number must be in [0..127]
```
